name: pmproject
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # network
  http: ^0.13.3
  http_interceptor: ^1.0.2
  logger: ^1.1.0
  dartz: ^0.10.1


  # db
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # getX
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

