name: pmproject
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # common
  page_transition: ^2.1.0
  lottie: ^2.7.0
  shake: ^2.2.0
#  webview_flutter: ^4.8.0
  flutter_linkify: ^6.0.0
  flutter_parsed_text: ^2.2.1

  # network
  http: ^0.13.3
  http_interceptor: ^1.0.2
  logger: ^1.1.0
  dartz: ^0.10.1
  cached_network_image: ^3.3.1

  # file
  image_picker: ^1.1.1

  # speech
  animated_text_kit: ^4.2.2
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2

  # db
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # getX
  get: ^4.6.6

  # firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1

  # internet
  connectivity_plus: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

